### PR TITLE
test_mellon_diagnostics

### PR DESCRIPTION
**Pull request by spoore1**
Add test_mellon_diagnostics to test_mellon.py so that we can directly
report results on the test in the junit.xml if generated.

### CODE REVIEW

**Comment by spoore1** [comment]
@jhrozek @thalman can one of you guys review this?

The only thing I can think of to add/change here is if I should wrap the test_mellon.sh diagnostics setup in a function to allow soft failure and then not run the test_mellon_diagnostics test case.  But, I think we want to know if we can't install the diagnostics package don't we?

**Comment by jhrozek** [comment]
This is cool and I'm going to ack the PR.
Would you consider as an additional improvement to look at the file size before the test, run the test and then again so we can re-run the test multiple times? Or just remove the diag file after the test?

**Comment by jhrozek** [comment]
> @jhrozek @thalman can one of you guys review this?
> 

LGTM

> The only thing I can think of to add/change here is if I should wrap the test_mellon.sh diagnostics setup in a function to allow soft failure and then not run the test_mellon_diagnostics test case. But, I think we want to know if we can't install the diagnostics package don't we?

I think it's fine.

**Review by jhrozek — APPROVED** [review]

**Comment by spoore1** [comment]
@jhrozek I updated the test to zero the diagnostics file before running the test.  I'm able to rerun it multiple times successfully.    I also added comments.  Can you take a quick look and let me know what you think?

**Review by jhrozek — APPROVED** [review]
Thank you for the changes, LGTM

**Pull request merged**
